version: '3.7'

services:
  express:
    build:
      context: .
      dockerfile: ./docker/express/Dockerfile.express
  cypress:
    build:
      context: .
      dockerfile: ./tests/Dockerfile.cypress
  docker-host:
    image: qoomon/docker-host:3.0.3
    cap_add: ['NET_ADMIN', 'NET_RAW']
    deploy:
      resources:
        limits:
          memory: 8M
    restart: on-failure
