FROM node:14.15.4

WORKDIR /sdk

COPY . /sdk

RUN npm install
RUN npm run build
RUN npm pack

FROM alpine

WORKDIR /sdk

COPY --from=0 /sdk/spree-storefront-api-v2-sdk-*.tgz /sdk/storefront-api-v2-sdk.tgz

COPY ./wait-for-it.sh /sdk/
